//USERS TEST

POST http://localhost:3001/users/create
Content-Type: application/json

{
	"username": "test",
    "password": "OOGA"
}

###

DELETE http://localhost:3001/users/delete/640fb6afdcd654601b071172

###

GET http://localhost:3001/users

###

PUT http://localhost:3001/users/edit/640fb6f4dcd654601b071183
Content-Type: application/json

{
	"username": "I AM CHANGED!!!",
    "password": "ooga booga"
}

###

GET http://localhost:3001/users/

###


POST http://localhost:3001/login
Content-Type: application/json

{
	"username" : "test",
	"password" : "OOGA"
}

###

// Posts test 

GET http://localhost:3001/posts

### 
POST http://localhost:3001/posts/create 
Content-Type: application/json

{
	"user": "TEST TEST TEST",
    "title": "GITHUB LINK TEST",
    "link": "https://github.com/",
    "content": "aeiurh aiuerh iuaehr uiae hriuae rbjaeb jhaeb fhjeab",
    "likes": 100
}

### 
POST http://localhost:3001/posts/create 
Content-Type: application/json

{
	"user": "seothset",
    "title": "kadhklaehfkljehfk",
    "content": "aeiurh aiuerh iuaehr uiae hriuae rbjaeb jhaeb fhjeab",
    "likes": 100
}


###
DELETE http://localhost:3001/posts/delete/640c1ecd7d06c3e34377014c

###

PUT http://localhost:3001/posts/edit/64128687c9dfc55f23f24e42
Content-Type: application/json

{
    "content": "bga"
}

### 
PUT http://localhost:3001/posts/likes/64128687c9dfc55f23f24e42
